name: Ready To the Code for deploying

on : [push , workflow_dispatch]

jobs:
  test-code :
    runs-on: ubuntu-latest
    steps:
      - name: copying the Code
        uses: actions/checkout@v6

      - name: Install Node-js
        uses: actions/setup-node@v6
        with:
          node-version: '23.11.0'

      - name: Check Node Version
        run: node -v 

      - name: Install Dependencies
        run : pnpm install --frozen-lockfile

      - name: Tests The codes
        run: pnpm run test 

        
